language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true
  
python:
  - 3.7

os:
  - linux

install: pip install -e .[tests,cov]

script: pytest --cov

after_success: coveralls