language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

notifications:
  email: false

git:
  depth: 3


install: pip install -e .[tests]

script: nosetests tests/test.py -v

after_success: 
  - coverage run tests/test.py -v
  - coveralls
